#!/usr/bin/env bash
# Script by Edward Stoever for Mariadb Support
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $SCRIPT_DIR


if [ ! -f ../vars.sh ]; then
  echo "../vars.sh does not exist. Exiting."; exit 1
fi

if [ ! -f ../functions.sh ]; then
  echo "../functions.sh does not exist. Exiting."; exit 1
fi

source ${SCRIPT_DIR}/../vars.sh
source ${SCRIPT_DIR}/../functions.sh
get_linux_type
OPTIONS_FILE='/etc/mysql/mariadb.conf.d/50-client.cnf' # DEFAULT (DEBIAN)
if [ "$LINUX_TYPE" == "REDHAT" ]; then OPTIONS_FILE='/etc/my.cnf.d/client.cnf'; fi

KEYFILE=$(ls $PUBLISH_DIR/$MY_ORGANIZATION.key 2>/dev/null)
ALLPURPOSEPEM=$(ls $PUBLISH_DIR/$MY_ORGANIZATION.pem 2>/dev/null)
CLIENTPEM=$(ls $PUBLISH_DIR/client_$MY_ORGANIZATION.pem 2>/dev/null)
SERVERPEM=$(ls $PUBLISH_DIR/server_$MY_ORGANIZATION.pem 2>/dev/null)
MYCA=$(ls $PUBLISH_DIR/myCA.pem 2>/dev/null)

if [ ! $CLIENTPEM ] && [ ! $ALLPURPOSEPEM ]; then echo "NO AVAILABLE PEM!"; exit 1; fi

if [ ! $CLIENTPEM ] && [ $ALLPURPOSEPEM ]; then
  DEMOPEM=$ALLPURPOSEPEM
else
  DEMOPEM=$CLIENTPEM
fi

OUTPUT="Note that for 11.4 and higher it is not necessary for you to configure
certificates. Certificates are auto-generated by the software. 

The following values are required for Galera to work properly with certificates.

Each node should have wsrep_node_address be a fully qualified domain name that 
matches one of the wildcard DNS values in the certificate. For example, if in the 
certificate, you have DNS.2 = *.edw.ee, you can use these values for three galera nodes:
wsrep_node_address = m1.edw.ee
wsrep_node_address = m2.edw.ee
wsrep_node_address = m3.edw.ee

To perform SST, you will need the global variables ssl-cert, ssl-key, ssl-ca 
defined. Run the script server.sh for instructions.

You must define wsrep_provider_options to include your certificates. 
This is an example:
wsrep_provider_options='socket.ssl=true; socket.ssl_ca=${MYCA}; socket.ssl_cert=${DEMOPEM}; socket.ssl_key=${KEYFILE}; cert.optimistic_pa=no; gcache.recover=yes; gcache.size=256M; gcs.fc_factor=0.8; gcs.fc_limit=96; gcs.fc_master_slave=yes;'

For SST to use the certificates, you should have the following [sst] group in one of your options files:
[sst]
ssl-mode=VERIFY_CA

When you perform an sst, it should succeed, and you should see your certificates in the database log, like this:
WSREP_SST: [INFO] SSL configuration: CA='${MYCA}', CAPATH='', CERT='${DEMOPEM}', KEY='${KEYFILE}', MODE='VERIFY_CA', encrypt='3' (20250225 14:41:55.972)


"

printf "${OUTPUT}"
